[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.19.0"
  YARN_VERSION = "1.22.22"
  CI = "false"

[dev]
  command = "yarn start"
  port = 3000
  targetPort = 3000
  framework = "create-react-app"
